apiVersion: v1
kind: Service
metadata:
  name: test-headless
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: gossip
    port: 3100
    protocol: TCP
    targetPort: gossip
  selector:
    app.kubernetes.io/name: test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
